### ISSUE TITLE
Milestone #1

### ISSUE THREAD

**Issue by Suzii** [ssvinciak/pv247-chatify#1]
# Status: ✔️ 
Below are just suggestions to consider for the next milestones.
Thumbs up for TypeScript 😉 
 
# Design suggestions
As far as the design goes, the app is a bit broken - you cannot see some characters like 'C' (Channels) etc. The fix is easy - wrap the `App` component's content with `container` css class. Generally, make sure you use the bootstrap classes correctly. See [this section of documentation](https://getbootstrap.com/docs/3.3/getting-started/#examples) to get an overview on how to structure the page with a navigation.
Single message could use more styling - try giving it more vertical space.
 
# Code suggestions
I hope to see no code commented out in the final submission 😉 
Function arguments should always be camelCase + string type in typescript is 'string' not 'String'. (https://github.com/ssvinciak/pv247-chatify/commit/5603cacab966770fbdf9bc9e9463d362c6cc35a8#diff-c8a101915dc6871f1f3d7ad2208d8655R25)
 
Image used in profile picture, should not be inlined like this. Use a normal image and import it to react component, then render it in src attribute (https://stackoverflow.com/questions/39999367/how-do-i-reference-a-local-image-in-react).
I see you have some todos to create more components like single message - yes, please do 😄 
`Const.ts.` file should have been rather something like `constants/appNames.ts`.

**Comment by stefanbartos** [comment]
I tried to use require for static image, but ts-lint displayed error message as follows: require() style import is forbidden so i used base64 encoding (for info about [rule](https://palantir.github.io/tslint/rules/no-require-imports/l)). What solution do you propose? @Suzii

**Comment by Suzii** [comment]
Well, did you try to save the image as jpg/png and then import the file?

**Comment by stefanbartos** [comment]
Yes, i've tried.

**Comment by Suzii** [comment]
So after a bit of googling, this solution seems to be working without any warnings https://github.com/ssvinciak/pv247-chatify/pull/2 😉

**Comment by mcvincekova** [comment]
Neat.
